# Data configuration

raw_data_path: data/raw/dataset.csv
processed_data_path: data/processed/
train_split: 0.8
validation_split: 0.1
test_split: 0.1

preprocessing:
  tokenizer: bert-base-uncased
  max_length: 512
  padding: max_length
  truncation: true
