# Training configuration

seed: 42
batch_size: 16
num_epochs: 10
learning_rate: 5e-5
weight_decay: 0.01
warmup_steps: 500
gradient_accumulation_steps: 2
max_grad_norm: 1.0

# Paths
output_dir: models/
log_dir: logs/
data_dir: data/processed/

# Hardware configuration
device: cuda
num_workers: 4
mixed_precision: true
